before_install:
    - sudo apt-get install python python-dev python3 python3-dev
    - sudo apt-get install python-setuptools python3-setuptools
    - sudo apt-get install python-pip python3-pip
    - sudo apt-get install libgmp3-dev
language: python
sudo: true
python:
    - "3.8"
    - "3.9"
    - "3.10"
    - "nightly"
install:
    - pip install -r requirements.txt
script:
    - pytest
notifications:
    email:
        - moustikitos@gmail.com
