before_install:
    - sudo apt-get install curl
    - sudo apt-get install python python-dev python3 python3-dev
    - sudo apt-get install python-setuptools python3-setuptools
    - sudo apt-get install python-pip python3-pip
    - sudo apt-get install libudev-dev libusb-1.0.0-dev
language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    pytest
