before_install:
    - sudo apt-get install python python-dev python3 python3-dev
    - sudo apt-get install python-setuptools python3-setuptools
    - sudo apt-get install python-pip python3-pip
    - sudo apt-get install libudev-dev libusb-1.0.0-dev
language: python
sudo: true
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"
install:
    - pip install -r requirements.txt
script:
    - pytest
notifications:
    email:
        - moustiktos@gmail.com
