copyright: Copyright &copy; 2016-2021 THOORENS Bruno - MIT licence
docs_dir: docs
markdown_extensions:
- toc:
    baselevel: 1
    permalink: '#'
nav:
- Home: index.md
- Network: network.md
- Crypto: crypto.md
- Blockchain: blockchain.md
repo_name: GitHub
repo_url: https://github.com/Moustikitos/dposlib
site_name: The dposlib Project
theme: mkdocs
