configuration = {u'data': {u'constants': {u'activeDelegates': 51,
                          u'block': {u'acceptExpiredTransactionTimestamps': False,
                                     u'idFullSha256': True,
                                     u'maxPayload': 6300000,
                                     u'maxTransactions': 150,
                                     u'version': 0},
                          u'blocktime': 8,
                          u'epoch': u'2017-03-21T13:00:00.000Z',
                          u'fees': {u'staticFees': {u'delegateRegistration': 2500000000L,
                                                    u'delegateResignation': 2500000000L,
                                                    u'ipfs': 0,
                                                    u'multiPayment': 0,
                                                    u'multiSignature': 500000000,
                                                    u'secondSignature': 500000000,
                                                    u'timelockTransfer': 0,
                                                    u'transfer': 10000000,
                                                    u'vote': 100000000}},
                          u'height': 9000000,
                          u'reward': 200000000,
                          u'vendorFieldLength': 255},
           u'explorer': u'https://explorer.ark.io',
           u'nethash': u'6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988',
           u'ports': {u'@arkecosystem/core-api': 4003,
                      u'@arkecosystem/core-p2p': None},
           u'slip44': 111,
           u'symbol': u'\u0466',
           u'token': u'ARK',
           u'transactionPool': {u'dynamicFees': {u'addonBytes': {u'delegateRegistration': 400000,
                                                                 u'delegateResignation': 100,
                                                                 u'ipfs': 250,
                                                                 u'multiPayment': 500,
                                                                 u'multiSignature': 500,
                                                                 u'secondSignature': 250,
                                                                 u'timelockTransfer': 500,
                                                                 u'transfer': 100,
                                                                 u'vote': 100},
                                                 u'enabled': True,
                                                 u'minFeeBroadcast': 3000,
                                                 u'minFeePool': 3000}},
           u'version': 23,
           u'wif': 170}}
fees = {u'data': [{u'avg': u'2269148',
            u'max': u'62596154',
            u'min': u'30000',
            u'sum': u'74405350052',
            u'type': 0},
           {u'avg': u'80000000',
            u'max': u'80000000',
            u'min': u'80000000',
            u'sum': u'80000000',
            u'type': 2},
           {u'avg': u'81991184',
            u'max': u'1000000000',
            u'min': u'558037',
            u'sum': u'3935576835',
            u'type': 3}],
 u'meta': {u'days': 7}}