configuration = {u'data': {u'constants': {u'activeDelegates': 53,
                          u'block': {u'idFullSha256': True,
                                     u'maxPayload': 8388608,
                                     u'maxTransactions': 250,
                                     u'version': 0},
                          u'blocktime': 12,
                          u'epoch': u'2019-08-01T08:00:00.000Z',
                          u'fees': {u'staticFees': {u'delegateRegistration': 2500000000L,
                                                    u'delegateResignation': 2500000000L,
                                                    u'ipfs': 0,
                                                    u'multiPayment': 0,
                                                    u'multiSignature': 500000000,
                                                    u'secondSignature': 500000000,
                                                    u'timelockTransfer': 0,
                                                    u'transfer': 10000000,
                                                    u'vote': 100000000}},
                          u'height': 50401,
                          u'reward': 800000000,
                          u'vendorFieldLength': 255},
           u'explorer': u'http://dev.hydra.iop.global',
           u'nethash': u'30b7368d1f78264d479c3adb38246ddde7cad58e72af51f1da9b27e04f4a005d',
           u'ports': {u'@arkecosystem/core-api': 4703,
                      u'@arkecosystem/core-p2p': None},
           u'slip44': 1,
           u'symbol': u'D\u0126',
           u'token': u'DHYD',
           u'transactionPool': {u'dynamicFees': {u'addonBytes': {u'delegateRegistration': 400000,
                                                                 u'delegateResignation': 100,
                                                                 u'ipfs': 250,
                                                                 u'multiPayment': 500,
                                                                 u'multiSignature': 500,
                                                                 u'secondSignature': 250,
                                                                 u'timelockTransfer': 500,
                                                                 u'transfer': 100,
                                                                 u'vote': 100},
                                                 u'enabled': True,
                                                 u'minFeeBroadcast': 1000,
                                                 u'minFeePool': 1000}},
           u'version': 90,
           u'wif': 85}}
fees = {u'data': [{u'avg': u'346725',
            u'max': u'360000',
            u'min': u'337000',
            u'sum': u'283968000',
            u'type': 0}],
 u'meta': {u'days': 7}}