configuration = {u'data': {u'constants': {u'activeDelegates': 51,
                          u'block': {u'acceptExpiredTransactionTimestamps': False,
                                     u'idFullSha256': True,
                                     u'maxPayload': 11000000,
                                     u'maxTransactions': 256,
                                     u'version': 0},
                          u'blocktime': 8,
                          u'epoch': u'2017-03-21T13:00:00.000Z',
                          u'fees': {u'staticFees': {u'delegateRegistration': 2500000000L,
                                                    u'delegateResignation': 2500000000L,
                                                    u'ipfs': 0,
                                                    u'multiPayment': 0,
                                                    u'multiSignature': 500000000,
                                                    u'secondSignature': 500000000,
                                                    u'timelockTransfer': 0,
                                                    u'transfer': 10000000,
                                                    u'vote': 100000000}},
                          u'height': 3710000,
                          u'reward': 1000000000,
                          u'vendorFieldLength': 255},
           u'explorer': u'https://explorer.qredit.io',
           u'nethash': u'5e67037fd290ba7ab378e84a591d251c46eb9770eb134983771fd602233bf193',
           u'ports': {u'@arkecosystem/core-api': 4103,
                      u'@arkecosystem/core-p2p': 4101},
           u'slip44': 1,
           u'symbol': u'XQR',
           u'token': u'XQR',
           u'transactionPool': {u'dynamicFees': {u'addonBytes': {u'delegateRegistration': 400000,
                                                                 u'delegateResignation': 100,
                                                                 u'ipfs': 250,
                                                                 u'multiPayment': 500,
                                                                 u'multiSignature': 500,
                                                                 u'secondSignature': 250,
                                                                 u'timelockTransfer': 500,
                                                                 u'transfer': 100,
                                                                 u'vote': 100},
                                                 u'enabled': True,
                                                 u'minFeeBroadcast': 3000,
                                                 u'minFeePool': 3000}},
           u'version': 58,
           u'wif': 187}}
fees = {u'data': [{u'avg': u'1264656',
            u'max': u'10000000',
            u'min': u'803831',
            u'sum': u'6243607987',
            u'type': 0},
           {u'avg': u'15097804',
            u'max': u'100000000',
            u'min': u'786480',
            u'sum': u'286858280',
            u'type': 3}],
 u'meta': {u'days': 7}}